set(ZLIB_CMAKE_ARGS
  -DZLIB_COMPAT=ON
  -DZLIB_ENABLE_TESTS=OFF
  -DWITH_GTEST=OFF
  -DZLIBNG_ENABLE_TESTS=OFF
  -DBUILD_SHARED_LIBS=OFF)

ExternalProject_Add(zlib-static
  URL                  ${ZLIB_URL}
  URL_HASH             SHA256=${ZLIB_SHA256}
  DOWNLOAD_NO_PROGRESS TRUE
  LOG_BUILD            ON
  DOWNLOAD_DIR         ${DEPS_DOWNLOAD_DIR}/zlib
  SOURCE_DIR           ${DEPS_BUILD_DIR}/src/zlib
  CMAKE_ARGS           ${DEPS_CMAKE_ARGS} ${ZLIB_CMAKE_ARGS}
  CMAKE_CACHE_ARGS     ${DEPS_CMAKE_CACHE_ARGS})
